
smart_module_user.edit:
    path: /edit
    defaults:
        _controller: UserModule:User:edit

smart_module_user.login:
    path: /login
    defaults:
        _controller: FOSUserBundle:Security:login

smart_module_user.change-password:
    path: /change-password
    defaults:
        _controller: UserModule:User:changePassword

# Resetting password
smart_module_user.resetting:
    path: /resetting/
    defaults:
        _controller: UserModule:User:resettingRequest

smart_module_user.resetting.send-email:
    path: /resetting/send-email
    defaults:
        _controller: FOSUserBundle:Resetting:sendEmail

smart_module_user.resetting.check-email:
    path: /resetting/check-email
    defaults:
        _controller: FOSUserBundle:Resetting:checkEmail

smart_module_user.resetting.reset:
    path: /resetting/reset/{token}
    defaults:
        _controller: FOSUserBundle:Resetting:reset

# Registration
smart_module_user.registration.index:
    path: /register/
    defaults:
        _controller: UserModule:User:register

smart_module_user.registration.check-email:
    path: /register/check-email
    defaults:
        _controller: UserModule:User:registerCheckEmail

smart_module_user.registration.confirm:
    path: /register/confirm/{token}
    defaults:
        _controller: FOSUserBundle:Registration:confirm

smart_module_user.registration.confirmed:
    path: /register/confirmed
    defaults:
        _controller: FOSUserBundle:Registration:confirmed
