
cms_api_index:
    path: /
    defaults:
        _controller: CMSBundle:ApiEngine:index

cms_api_node_index:
    path: /{node_id}/
    defaults:
        _controller: CMSBundle:ApiEngine:node
        slug: ""
    requirements:
        slug: ".+"
        node_id: \d+

cms_api_node:
    path: /{node_id}/{slug}
    defaults:
        _controller: CMSBundle:ApiEngine:node
        slug: ""
    requirements:
        slug: ".+"
        node_id: \d+

#cms_api_index:
#    path: /{object}/
#    defaults:
#        _controller: CMSBundle:ApiEngine:run

#cms_api:
#    path: /{object}/{slug}
#    defaults:
#        _controller: CMSBundle:ApiEngine:run
#        slug: ""
#    requirements:
#        slug: ".+"
