services:
    db.logger:
        class: Doctrine\DBAL\Logging\DebugStack

# Listeners
    cms.controller.listener:
        class: SmartCore\Bundle\CMSBundle\Listener\ModuleControllerModifierListener
        arguments: [ @cms.context, @cms.node ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onController }
    cms.request.listener:
        class: SmartCore\Bundle\CMSBundle\Listener\ModuleControllerModifierListener
        arguments: [ @cms.context, @cms.node ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
    cms.response.listener:
        class: SmartCore\Bundle\CMSBundle\Listener\ModuleControllerModifierListener
        arguments: [ @cms.context, @cms.node ]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
    cms.view.listener:
        class: SmartCore\Bundle\CMSBundle\Listener\ModuleControllerModifierListener
        arguments: [ @cms.context, @cms.node ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onView }
    cms.db.table_prefix_subscriber:
        class: SmartCore\Bundle\CMSBundle\Listener\TablePrefixSubscriber
        arguments: [%database_table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
# Core
    cms.block:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineBlock
        arguments: [ @doctrine.orm.default_entity_manager, @form.factory ]
    cms.context:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineContext
        arguments: [ @service_container ]
    cms.folder:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineFolder
        arguments: [ @service_container ]
    cms.module:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineModule
        arguments: [ @kernel ]
    cms.cache:
        class: SmartCore\Bundle\CMSBundle\Engine\Cache
        arguments: [ '%kernel.cache_dir%' ]
    cms.node:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineNode
        arguments:
            - @doctrine.orm.default_entity_manager
            - @form.factory
            - @kernel
            - @cms.context
            - "%database_table_prefix%"
    cms.theme:
        class: SmartCore\Bundle\CMSBundle\Engine\Theme
        calls:
            - [ setContainer, [ @service_container ] ]
    cms.jslib:
        class: SmartCore\Bundle\CMSBundle\Engine\JavaScriptLibrary
        arguments: [ @database_connection, @cms.context ]
    cms.router:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineRouter
        calls:
            - [ setContainer, [ @service_container ] ]
    cms.routes.module_admin.loader:
        class: SmartCore\Bundle\CMSBundle\Router\ModuleAdminRoutesLoader
        arguments: [ @database_connection, @cms.context ]
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setResolver,  [ @routing.resolver ] ]
        tags:
            - { name: routing.loader }
    cms.toolbar:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineToolbar
        calls:
            - [ setContainer, [ @service_container ] ]
# Forms
    cms.form.type.extension.node_id:
        class: SmartCore\Bundle\CMSBundle\Form\Extension\FormTypeNodeIdExtension
        arguments: [ @cms.context ]
        tags:
            - { name: form.type_extension, alias: form }
    cms.form.type.folder_tree:
        class: SmartCore\Bundle\CMSBundle\Form\Tree\FolderTreeType
        arguments: [ @doctrine ]
        tags:
            - { name: form.type, alias: folder_tree }
# Twig
    cms.twig.block_extension:
        class: SmartCore\Bundle\CMSBundle\Twig\BlockExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }

    cms.twig.engine_path_extension:
        class: SmartCore\Bundle\CMSBundle\Twig\CmsModulePathExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

# Menu selected items
    cms.menu.voter.request:
        class: SmartCore\Bundle\CMSBundle\Menu\RequestVoter
        arguments:
            - @request_stack
        tags:
            - { name: knp_menu.voter }
