imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@SmartCoreEngineBundle/Resources/config/config.yml" }

framework:
    annotations:
        debug:       %kernel.debug%
    csrf_protection:
        enabled:     true
    default_locale:  %locale%
    esi:             
        enabled:     false
    form:            true
    validation:      { enable_annotations: true }
    profiler:
        enabled:     false
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    secret:          %secret%
    session:
        handler_id: smart_core_session.handler
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    translator:      { fallback: en }

fm_elfinder:
    locale: %locale% # defaults to current request locale
    editor: ckeditor # other choices are tinymce or simple
    showhidden: false # defaults to false
    fullscreen: true # defaults true, applies to simple and ckeditor editors
    include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
    compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
    connector:
        debug: true # defaults to false
        roots:       # at least one root must be defined
            uploads:
                driver: LocalFileSystem
                path: uploads
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                upload_deny: ['all']
                upload_max_size: 2M

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: false
    autoescape:       false

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [FMElfinderBundle]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                logging:  %kernel.debug%
                unix_socket: /var/run/mysqld/mysqld.sock
                mapping_types:
                    enum: string                
            db1:
                driver:   %database_driver_db1%
                port:     %database_port_db1%
                dbname:   %database_name_db1%
                user:     %database_user_db1%
                password: %database_password_db1%
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
        type:  file
        path:  %kernel.root_dir%/../var/mailspool

smart_core_engine:
    storage: database

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: SmartCore\Bundle\FOSUserBundle\Entity\User
    registration:
        confirmation:    
            enabled: true
            from_email:
                address: %registration_email_confirmation%
                sender_name: Email confirmation
