
smart_texter_api:
    path: /
    methods: 'GET'
    defaults:
        _controller: TexterModule:ApiTexter:json

smart_texter_api_html:
    path: /html
    methods: 'GET'
    defaults:
        _controller: TexterModule:ApiTexter:html

smart_texter_api_html_w_slash:
    path: /html/
    methods: 'GET'
    defaults:
        _controller: TexterModule:ApiTexter:html
