
smart_texter_admin:
    path: /
    defaults:
        _controller: TexterModule:Admin:index

smart_texter_admin_history:
    path: /{id}/history
    defaults:
        _controller: TexterModule:Admin:history
    requirements:
        id: \d+

smart_texter_admin_rollback:
    path: /rollback/{id}/
    defaults:
        _controller: TexterModule:Admin:rollback
    requirements:
        id: \d+

smart_texter_admin_edit:
    path: /{id}/
    defaults:
        _controller: TexterModule:Admin:item
    requirements:
        id: \d+
